### ISSUE TITLE
Stream URLs return 403 in 3.2.0

### ISSUE THREAD

**Issue by em-ex** [thebigmunch/google-music#11]
I decided to update this amazing library. 
First, I encountered an issue with httpx - apparently only v0.7.8 had a middleware package (from which the library imports basic_auth), but the current version 0.8.0 does not. 

So I went and installed the former, but now am facing 403 errors while trying to obtain a stream URL:
```
Traceback (most recent call last):
  File "D:\CODE\PYTHON\gmus\gmus_test.py", line 900, in <module>
    dirname = getAlbum(data)
  File "D:\CODE\PYTHON\gmus\gmus_test.py", line 819, in getAlbum
    url = gm.stream_url(track)
  File "C:\Program Files\Python36\lib\site-packages\google_music\clients\mobileclient.py", line 1996, in stream_url
    device_id=device_id,
  File "C:\Program Files\Python36\lib\site-packages\tenacity\__init__.py", line 292, in wrapped_f
    return self.call(f, *args, **kw)
  File "C:\Program Files\Python36\lib\site-packages\tenacity\__init__.py", line 358, in call
    do = self.iter(retry_state=retry_state)
  File "C:\Program Files\Python36\lib\site-packages\tenacity\__init__.py", line 331, in iter
    raise retry_exc.reraise()
  File "C:\Program Files\Python36\lib\site-packages\tenacity\__init__.py", line 167, in reraise
    raise self.last_attempt.result()
  File "C:\Program Files\Python36\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "C:\Program Files\Python36\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Program Files\Python36\lib\site-packages\tenacity\__init__.py", line 361, in call
    result = fn(*args, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\google_music\clients\base.py", line 215, in _call
    response.raise_for_status()
  File "C:\Program Files\Python36\lib\site-packages\httpx\models.py", line 920, in raise_for_status
    raise HTTPError(message, response=self)
httpx.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://mclients.googleapis.com/music/mplay?hl=en_US&tier=aa&alt=json&dv=0&locale=en_US&audio_formats=mp3&net=mob&opt=hi&pt=e&sig=b%27[redacted]%27&slt=[redacted]&mjck=[redacted]
For more information check: https://httpstatuses.com/403
```
Works perfectly fine for the same URL with google-music v3.0.1.

**Comment by thebigmunch** [comment]
httpx decided to remove their sync support (go async-only) until some later date with v0.8.0, so that version would never work anyway. I just haven't changed the version constraint to be ``0.7.8`` or do some magic to get the async version to work.

I can't reproduce any 403s here, so I'd check if it is only a specific song or all of them. I did, however, find an issue with ``Mobileclient.stream`` that may be related to an httpx difference.

**Comment by thebigmunch** [comment]
Closing due to lack of response and being unable to reproduce.
