### ISSUE TITLE
Broken with latest httpx (0.9.3)

### ISSUE THREAD

**Issue by bendardenne** [thebigmunch/google-music#12]
Hi,

I'm trying to install this on a new system. Running `pip install google-music` installs version 3.2.0 of the library together with httpx version 0.9.3.  

Trying to import google_music then results in an error: 

```
Python 3.6.9 (default, Nov  7 2019, 10:44:02)                                              
[GCC 8.3.0] on linux                                                         
Type "help", "copyright", "credits" or "license" for more information.           
>>> import google_music                                                                                 
Traceback (most recent call last):                                                                      
  File "<stdin>", line 1, in <module>                                                                   
  File "/home/bdardenn/.local/lib/python3.6/site-packages/google_music/__init__.py", line 2, in <module>
    from .api import *                                                                               
  File "/home/bdardenn/.local/lib/python3.6/site-packages/google_music/api.py", line 6, in <module>  
    from .clients import MobileClient, MusicManager                                                     
  File "/home/bdardenn/.local/lib/python3.6/site-packages/google_music/clients/__init__.py", line 1, in
<module>                                                                                     
    from .mobileclient import *
  File "/home/bdardenn/.local/lib/python3.6/site-packages/google_music/clients/mobileclient.py", line 18
, in <module>
    from .base import GoogleMusicClient
  File "/home/bdardenn/.local/lib/python3.6/site-packages/google_music/clients/base.py", line 8, in <mod
ule>
    from httpx.middleware.basic_auth import BasicAuthMiddleware as HTTPBasicAuth
ModuleNotFoundError: No module named 'httpx.middleware.basic_auth'; 'httpx.middleware' is not a package
```

I guess the API of httpx has changed.

As a workaround, I have forced httpx to version 0.7.5.

**Comment by thebigmunch** [comment]
Yeah, I have been busy, so I haven't gotten around to changing the httpx version since they went async-only while they rethink how they want to do sync. With something they did that actually intentionally broke Python 3.6 compatibility then reversed after I complained (loudly), ``0.7.8`` will be the only version that properly supports everything it should, but ``0.7.5`` and ``0.7.6`` should work if you're on Python 3.7 or 3.8.
